services:
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mysql
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  mongo:
    image: "mongo"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mysql:
    image: "mysql:latest"
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
      - ./seeder/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: store
      MYSQL_USER: api
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_root_password
      - db_password

  api:
    restart: always
    environment:
      MONGO_DB: cloud
      MONGO_USER: root
      MONGO_HOST: mongo
      MONGO_PASS: example
      MYSQL_DB: cloud
      MYSQL_USER: root
      MYSQL_HOST: mysql
      MYSQL_PASS_FILE: /run/secrets/db_root_password
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 8050
      PYTHONUNBUFFERED: 1
      ENV_FILE_LOCATION: .env.local
    build: .
    volumes:
      - .:/app
      - /var/run/libvirt:/var/run/libvirt
    ports:
      - 8050:8050
    secrets:
      - db_root_password
      - db_password

  # looper:
  #   restart: always
  #   environment:
  #     api: api
  #     port: 8050
  #     PYTHONUNBUFFERED: 1
  #     LIBVIRT_DEFAULT_URI: qemu://system
  #   volumes:
  #     - .:/app
  #     - /var/run/libvirt:/var/run/libvirt
  #   build:
  #     dockerfile: ./Dockerfile-looper
  #     context: .


secrets:
  db_password:
    file: .secrets/db_password.txt
  db_root_password:
    file: .secrets/db_root_password.txt
  JWT_SECRET_KEY:
    file: .secrets/JWT_SECRET_KEY.txt

volumes:
  data: {}
