# syntax=docker/dockerfile:1

FROM python:3.8

LABEL autor="Michal Goryszewski"
LABEL version="1.0.1"

WORKDIR /app

RUN apt update && apt  install libvirt-clients libvirt-dev -y

COPY ["req-looper.txt" ,"./req.txt"]
RUN pip3 install -r req.txt

COPY . .

CMD [ "python3" ,"looper.py" ]
